### ISSUE TITLE
大神，webhooks应该要配置头文件格式为json吧？

### ISSUE THREAD

**Issue by lucasjinreal** [yanglbme/v2ex-action#3]
![image](https://user-images.githubusercontent.com/21303438/84642046-813f7f00-af2e-11ea-9f0c-14480ef0b42c.png)

Should be json?

**Comment by lucasjinreal** [comment]
```
something error occurred, message: Invalid URL '&timestamp=1592214040442&sign=HitEwl5VmKNPszafvqOn4%2BH%2FVYYqiBK2YLGf%2FpzAG58%3D': No schema supplied. Perhaps you meant http://&timestamp=1592214040442&sign=HitEwl5VmKNPszafvqOn4%2BH%2FVYYqiBK2YLGf%2FpzAG58%3D?
```

actions里面报这个错

**Comment by yanglbme** [comment]
你这是企业微信机器人吧？企业微信机器人的配置很简单，参考 https://github.com/yanglbme/weekly-reading/blob/master/.github/workflows/v2ex.yml

WEBHOOK 就是这个。

![image](https://user-images.githubusercontent.com/21008209/84646625-fdd55c00-af34-11ea-87eb-3d4551928803.png)

**Comment by lucasjinreal** [comment]
@yanglbme 感谢回复，对的，是企业微信的，我是粘贴的这个webhook地址，并且在repo的wehooks里面配置了，但是我看action的后台输出有错误，就是我上面贴的这个问题。

貌似也没有消息发到群里。咋回事

**Comment by yanglbme** [comment]
@jinfagang 你好，参数名必须是 `webhook`，你看命名有没有错，你也可以把你的 `.yml` 文件发出来我看看。

根据这个报错信息，应该是调用了钉钉机器人了。


---

我刚才自己又重新测了一遍，创建了企业机器人，结果是可以的。

![image](https://user-images.githubusercontent.com/21008209/84727762-5272e880-afc2-11ea-837c-961fb84a26df.png)

可以准确获取 V 站的热门帖子。

![image](https://user-images.githubusercontent.com/21008209/84727800-720a1100-afc2-11ea-85b5-40f53f1435d9.png)

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/84729203-b3e88680-afc5-11ea-9f06-a07ceb67bf7c.png)

**Comment by lucasjinreal** [comment]
看起来我的这个 secrets.WEBHOOK 应该改为 webhook.WEBHOOK?

**Comment by yanglbme** [comment]
不是的，前缀 `secrets.` 是固定的，因为我们是将敏感字段放到 secrets 下。

![image](https://user-images.githubusercontent.com/21008209/84730301-64f02080-afc8-11ea-8ca1-65ff81d30d8d.png)

应该在 secrets 配置一个名字为 `WEBHOOK` 的密钥。

**Comment by lucasjinreal** [comment]
感谢，working了
